blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/minagishl/void/discussions
    about: For questions and discussions, please use the Discussions section.
